# Generated by Django 3.0.2 on 2020-01-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='Photo_Caption')),
                ('status', models.CharField(max_length=255, verbose_name='Photo_Status')),
                ('url', models.CharField(max_length=500, verbose_name='Photo_Url')),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('changed_on', '-changed_on'),
            },
        ),
    ]
